global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'PRODUCT-CATALOG-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.33.4:8810']
        labels:
          application: 'Product Catalog Service Application'
  - job_name: 'CUSTOMER-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.33.4:8811']
        labels:
          application: 'Customer Service Application'
